# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CDA
                                 A QGIS plugin
 The Coastal Dynamics Analyzer (CDA) is a new plugin for QGIS, developed to provide an automatic method for Shoreline Change Analysis (SCA), improving the accuracy and speed of the analysis.The CDA plugin is written in PyQGIS (version v.1.0.0). It allows you to define a piecewise polynomial baseline and generate transects for shoreline change analysis. CDA allows commonly used rate-of-change such as End Point Rate (EPR), Net Shoreline Movement (NSM), Shoreline Change Envelope (SCE), and Linear Regression Rate (LRR) to be calculated, providing reports in .csv and shapefile formats. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-07-24
        copyright            : (C) 2024 by Scala et al., 2024 - UNIVERSITY OF PALERMO, MARINE AND COASTAL ENGINEERING LAB
        email                : pietro.scala@unipa.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Scala et al., 2024 - UNIVERSITY OF PALERMO, MARINE AND COASTAL ENGINEERING LAB'
__date__ = '2024-07-24'
__copyright__ = '(C) 2024 by Scala et al., 2024 - UNIVERSITY OF PALERMO, MARINE AND COASTAL ENGINEERING LAB'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CDA class from file CDA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .CDA import CDAPlugin
    return CDAPlugin()
