# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CDA
                                 A QGIS plugin
 The Coastal Dynamics Analyzer (CDA) is a new plugin for QGIS, developed to provide an automatic method for Shoreline Change Analysis (SCA), improving the accuracy and speed of the analysis.The CDA plugin is written in PyQGIS (version v.1.0.0). It allows you to define a piecewise polynomial baseline and generate transects for shoreline change analysis. CDA allows commonly used rate-of-change such as End Point Rate (EPR), Net Shoreline Movement (NSM), Shoreline Change Envelope (SCE), and Linear Regression Rate (LRR) to be calculated, providing reports in .csv and shapefile formats. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-07-24
        copyright            : (C) 2024 by Scala et al., 2024 - UNIVERSITY OF PALERMO, MARINE AND COASTAL ENGINEERING LAB
        email                : pietro.scala@unipa.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Scala et al., 2024 - UNIVERSITY OF PALERMO, MARINE AND COASTAL ENGINEERING LAB'
__date__ = '2024-07-24'
__copyright__ = '(C) 2024 by Scala et al., 2024 - UNIVERSITY OF PALERMO, MARINE AND COASTAL ENGINEERING LAB'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .CDA_provider import CDAProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class CDAPlugin(object):

    def __init__(self):
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = CDAProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
